### ISSUE TITLE
Argument matching

### ISSUE THREAD

**Issue by samcragg** [roscopeco/moxy#6]
Would it be possible to rename the `custom` argument matcher with something a bit easier to remember, such as `matches`?

Thanks

**Comment by roscopeco** [comment]
While `custom` is mostly used to apply a lambda matcher, this is actually a _side effect_ of it's main purpose, which is to allow custom `MoxyMatcher` implementations to be used. In the general case the two are interchangable, but `custom` also allows matchers that do _custom_ stack manipulation to be added. 

For this reason, `custom` stays, but `matches` has been added (along with primitive variants) as a new matcher type (e.g. `Matchers.matches(arg -> arg.whatever(...))`).

As well as being easier to remember, this will hopefully make the distinction clearer in the API too 🙂 

Change is in develop, and slated for 0.92.0 release.

Thanks! 👍
